# Generated by Django 5.1.1 on 2024-11-08 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('mota', models.TextField(blank=True, null=True)),
                ('don_vi_tinh', models.CharField(choices=[('Kg', 'Kg'), ('Cái', 'Cái'), ('Chai', 'Chai'), ('Hộp', 'Hộp')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhoHangHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hanghoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlkhohang.hanghoa')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlkhohang.kho')),
            ],
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='kho',
            field=models.ManyToManyField(related_name='hanghoa', through='qlkhohang.KhoHangHoa', to='qlkhohang.kho'),
        ),
    ]
